# @package _global_
model:
  name: GradientBoostingClassifier
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3
  subsample: 1.0

hydra:
  sweeper:
    params:
        model.n_estimators: range(50, 200, step=50)
        model.learning_rate: range(0.01, 0.2, step=0.05)
        model.max_depth: range(3, 10, step=2)