# @package _global_
propensity_model:
  _target_: sklearn.ensemble.RandomForestClassifier
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  bootstrap: true
  class_weight: balanced

hydra:
  sweeper:
    params:
      propensity_model.n_estimators: range(50, 300, step=50)
      propensity_model.max_depth: range(5, 20, step=5)
