defaults:
  - _self_
  - propensity_model: LogisticRegression
  - revenue_model: RandomForest
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

seed : 42
data:
  raw_excel_path: "../data/raw/DataScientist_CaseStudy_Dataset.xlsx"
  sheets:
    - "Soc_Dem"
    - "Products_ActBalance"
    - "Inflow_Outflow"
    - "Sales_Revenues"

products:
  - CL
  - MF
  - CC

targets:
  propensity: Sale
  revenue: Revenue

preprocessing:
  features :
    numeric:
      - Age
      - Tenure
      - Count_CA
      - Count_SA
      - Count_MF
      - Count_OVD
      - Count_CC
      - Count_CL
      - ActBal_CA
      - ActBal_SA
      - ActBal_MF
      - ActBal_OVD
      - ActBal_CC
      - ActBal_CL
      - VolumeCred
      - VolumeCred_CA
      - TransactionsCred
      - TransactionsCred_CA
      - VolumeDeb
      - VolumeDeb_CA
      - VolumeDebCash_Card
      - VolumeDebCashless_Card
      - VolumeDeb_PaymentOrder
      - TransactionsDeb
      - TransactionsDeb_CA
      - TransactionsDebCash_Card
      - TransactionsDebCashless_Card
      - TransactionsDeb_PaymentOrder
  categorical:
    - Sex
  numeric_imputer:
    strategy: constant
    fill_value: 0
  categorical_imputer:
    strategy: constant
    fill_value: missing
  onehot:
    handle_unknown: ignore
  train_test_split:
    test_size: 0.2
    random_state: ${seed}

optimization:
  contact_limit: 100
  single_offer_per_client: true
  diversification:
    enabled: false
    min_fraction_per_product: 0.2
  robust:
    enabled: false
    confidence_level: 0.95
  save_path: "./results/optimized_offers.csv"

evaluation:
  metrics:
    - total_revenue
    - revenue_per_contact
    - acceptance_rate
    - roi
  cost_per_contact: 1.0

inference:
  output_dir: "./inference"
  propensity_file: "propensity_predictions.csv"
  revenue_file: "revenue_predictions.csv"

training:
  k_folds: 5
  random_seed: ${seed}
  propensity_scoring: "f1"
  revenue_scoring: "neg_root_mean_squared_error"
  model_dump_path: "./models"
  load_model_path: "./models"
  sample_fraction: 1.0
  train_enabled: true

mlflow:
  enabled: true
  tracking_uri: ${oc.env:MLFLOW_TRACKING_URI, "http://localhost:5000"}
  experiment_name: ${oc.env:MLFLOW_EXPERIMENT_NAME, "direct_marketing"}

hydra:
  sweeper:
    sampler:
      seed: 42
    direction: maximize
    study_name: "direct-marketing-optimization"
    storage: null
    n_trials: 1
    n_jobs: -1
