# @package _global_
revenue_model:
  _target_: sklearn.ensemble.GradientBoostingRegressor
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3
  loss: "squared_error"

hydra:
  sweeper:
    params:
      revenue_model.n_estimators: range(50, 200, step=50)
      revenue_model.learning_rate: range(0.01, 0.2, step=0.05)
      revenue_model.max_depth: range(3, 10, step=2)
