# @package _global_
revenue_model:
  _target_: sklearn.ensemble.RandomForestRegressor
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  bootstrap: true

hydra:
  sweeper:
    params:
      revenue_model.n_estimators: range(50, 200, step=10)
      revenue_model.max_depth: choice(None, 10, 20, 30)
      revenue_model.min_samples_split: range(2, 11)
      revenue_model.min_samples_leaf: range(1, 11)
      revenue_model.max_features: choice("sqrt", "log2")
      revenue_model.bootstrap: choice(true, false)
